# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Lule Sami spellchecker (Norway/Sweden)"
smj = "Julevsáme duollatjállemdárkastus (Vuodna/Svierik)"
se  = "Julevsámi čállindárkisteaddji (Norgga/Ruoŧŧa)"
sma = "Julevsaemien staeriedimmiedïrregh (Nöörje/Sveerje)"
nb  = "Lulesamisk stavekontroll (Norge/Sverige)"
sv  = "Lulesamisk rättstavning (Norge/Sverige)"
fi  = "Julevsaamen oikoluku (Norja/Ruotsi)"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Lule Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
smj = "TRANSLATE: A spellchecker for Lule Sami, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.smj"

[windows]
system_product_code = "{125C4606-53FD-4854-AECE-6A7DDAEA2BC7}_is1"
legacy_product_codes = [
    { value = "5839214E-BB51-4B0C-9869-68EFEE74BB1F", kind = "nsis" },
    { value = "4C648C69-615F-5610-AB36-D237CD9019B0", kind = "nsis" }
]
extra_locales = { smj-SE = "smj", smj-NO = "smj" }

[package.speller]
name = "Lule Sami"
version = "4.5.1"

[package.grammar]
name = "Lule Sami"
version = "1.0.0"

[package.tts-textproc]
name = "Lule Sami"
version = "0.1.0"

[package.hyphenator]
name = "Lule Sami"
version = "0.1.0"
