template = "https://github.com/giellalt/template-lang-und"
rev_id = 277
template_sha = "c0f383639e245d1daebce6e2006904e442eef1fd"

[replacements]
__GLOTTOLOG_ID__ = "lule1254"
__REPO__ = "lang-smj"
__UND2C__ = "smj"
__UNDEFINED__ = "Lule Sami"
__UND__ = "smj"
